# Uncomment the next line to define a global platform for your project
platform :ios, '14.4'

target 'swift-proj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwiftExample

    pod 'RxSwift'
    pod 'RxCocoa'

end

